# Generated by Django 4.1 on 2022-08-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_keysearch'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='static/video/%y')),
            ],
        ),
        migrations.DeleteModel(
            name='GetLink',
        ),
        migrations.AlterField(
            model_name='keysearch',
            name='genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
