# Generated by Django 4.1 on 2022-08-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_finalvideo_delete_getlink_alter_keysearch_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalvideo',
            name='video',
            field=models.FileField(upload_to='video/%y'),
        ),
    ]
