# Generated by Django 4.1 on 2022-08-24 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_alter_finalvideo_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FinalVideo',
        ),
    ]
