# Generated by Django 4.1 on 2022-08-26 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_delete_finalvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keysearch',
            name='genre',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
